pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 -p 5000:5000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy for staging') {
            when {
                branch 'develop'
            }
            steps {
                echo 'Deployed to staging'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'production'
            }
            steps {
                echo 'Deployed to production'
            }
        }
        stage('Deploy feature') {
          when {
            not {
              anyOf {
              branch 'master'
              branch 'develop'
              }
            }
          }
          steps {
            echo 'Feature deployed'
          }
        }
    }
}
